build.gradle.kts, src/main/resources/data.sql, src/main/resources/schema.sql
closed #11 
- 🛠️ schema.sql 수정
- 🛠️ data.sql 수정
=> [Chore] #11 - H2전용 테이블명 변경

src/main/java/org/example/kuit_kac/domain/diet/model/Diet.java, src/main/java/org/example/kuit_kac/domain/diet/model/DietType.java, src/main/java/org/example/kuit_kac/domain/dietTemplate/model/DietTemplate.java, src/main/java/org/example/kuit_kac/domain/food/model/Food.java, src/main/java/org/example/kuit_kac/domain/meal/model/Meal.java, src/main/java/org/example/kuit_kac/domain/meal/model/MealType.java, src/main/java/org/example/kuit_kac/domain/meal_food/model/MealFood.java, src/main/java/org/example/kuit_kac/domain/user/model/GenderType.java, src/main/java/org/example/kuit_kac/domain/user/model/User.java
closed #8 
- 🛠️ 각종 Model 추가
- 🛠️ Enum 추가
- 🛠️ NamedEntityGraphs 추가
=> [Feat] #8 - model 추가

src/main/java/org/example/kuit_kac/config/SecurityConfig.java, src/main/java/org/example/kuit_kac/exception/ErrorCode.java, src/main/java/org/example/kuit_kac/exception/GlobalExceptionHandler.java
closed #14 
- 🛠️ ErrorCode 추가
- 🛠️ SecurityConfig 추가
=> [Chore] #14 - ErrorCode 및 Config 추가

src/main/java/org/example/kuit_kac/domain/diet/dto/DietResponse.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietWithMealsAndFoodsResponse.java, src/main/java/org/example/kuit_kac/domain/diet/repository/DietRepository.java, src/main/java/org/example/kuit_kac/domain/diet/service/DietService.java, src/main/java/org/example/kuit_kac/domain/food/controller/FoodController.java, src/main/java/org/example/kuit_kac/domain/food/dto/FoodResponse.java, src/main/java/org/example/kuit_kac/domain/food/repository/FoodRepository.java, src/main/java/org/example/kuit_kac/domain/food/service/FoodService.java, src/main/java/org/example/kuit_kac/domain/meal/dto/MealResponse.java, src/main/java/org/example/kuit_kac/domain/meal/dto/MealWithFoodsResponse.java, src/main/java/org/example/kuit_kac/domain/meal/repository/MealRepository.java, src/main/java/org/example/kuit_kac/domain/meal/service/MealService.java, src/main/java/org/example/kuit_kac/domain/meal_food/dto/MealFoodItemResponse.java, src/main/java/org/example/kuit_kac/domain/user/controller/UserController.java, src/main/java/org/example/kuit_kac/domain/user/dto/UserResponse.java, src/main/java/org/example/kuit_kac/domain/user/repository/UserRepository.java, src/main/java/org/example/kuit_kac/domain/user/service/UserService.java
closed #16 
- 🛠️ dto 추가
- 🛠️ repository 추가
- 🛠️ service 추가
- 🛠️ controller 추가
=> [Feat] #16 - domain 추가

src/main/java/org/example/kuit_kac/domain/diet/model/DietType.java, src/main/java/org/example/kuit_kac/domain/meal/model/MealType.java, src/main/java/org/example/kuit_kac/domain/user/model/GenderType.java
closed #18 
- 🛠️ ENUM 클래스 모두 대문자로 변경
- 🛠️ 식단에 FASTING추가
=> [Chore] #18 - ENUM 클래스 대문자로 변경

src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java, src/main/java/org/example/kuit_kac/domain/food/controller/FoodController.java, src/main/java/org/example/kuit_kac/domain/meal/controller/MealController.java, src/main/java/org/example/kuit_kac/domain/user/controller/UserController.java
closed #29 
- 🛠️ PathVariable을 직접 명시합니다.
=> [Fix] #29 - PathVariable 파라미터 명시

src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java, src/main/java/org/example/kuit_kac/domain/diet/repository/DietRepository.java, src/main/java/org/example/kuit_kac/domain/diet/service/DietService.java
=> [Feat] #50 - 나만의 식단 조회 API

build.gradle.kts, src/main/java/org/example/kuit_kac/config/GptConfig.java, src/main/java/org/example/kuit_kac/domain/ai/controller/AiController.java
=> [Feat] #56 - ChatGpt API 구현 #5

src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietPlanCreateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietPlanUpdateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietRecordCreateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietRecordUpdateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/service/DietService.java, src/main/resources/data.sql
closed #58
- 🛠️ record / plan API 분리
=> [Feat] #58 - 계획 api 분리

src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java
=> [Feat] #60 - 식단 delete API 통합

src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietPlanCreateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietPlanUpdateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietRecordCreateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietRecordProfileResponse.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietRecordUpdateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/service/DietService.java, src/main/java/org/example/kuit_kac/domain/diet_food/dto/DietFoodSnackCreateRequest.java, src/main/java/org/example/kuit_kac/domain/diet_food/service/DietFoodService.java
closed #62
- 🛠️ 시간을 입력하면 자동으로 오늘의 날짜로 대입됩니다.
=> [Feat] #62 - API request 시간 수정

src/main/java/org/example/kuit_kac/domain/home/service/CoachReportService.java, src/main/java/org/example/kuit_kac/domain/home/service/HomeNutritionService.java, src/main/java/org/example/kuit_kac/domain/home/service/HomeSummaryService.java, src/main/java/org/example/kuit_kac/domain/routine/dto/RoutineTemplateCreateRequest.java, src/main/java/org/example/kuit_kac/global/util/TimeRange.java
=> [Merge] #66 - 메소드 불일치 수정하여 merge

src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietPlanCreateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietPlanUpdateRequest.java, src/main/java/org/example/kuit_kac/domain/diet/dto/DietRecordProfileResponse.java, src/main/java/org/example/kuit_kac/domain/diet/repository/DietRepository.java, src/main/java/org/example/kuit_kac/domain/diet/service/DietService.java, src/main/java/org/example/kuit_kac/global/util/TimeGenerator.java
closed #69
- 🛠️ 계획에 날짜를 추가하여 다른 날짜도 계획할 수 있도록 합니다.
=> [Feat] #69 - 계획에 날짜 추가

src/main/java/org/example/kuit_kac/domain/routine/controller/RoutineController.java, src/main/java/org/example/kuit_kac/domain/routine/dto/RoutineSimpleCreateRequest.java, src/main/java/org/example/kuit_kac/domain/routine/model/RoutineExercise.java, src/main/java/org/example/kuit_kac/domain/routine/model/TargetMuscleType.java, src/main/java/org/example/kuit_kac/domain/routine/service/RoutineExerciseService.java, src/main/java/org/example/kuit_kac/domain/routine/service/RoutineService.java, src/main/resources/data.sql, src/main/resources/schema.sql
closed #77
- 🛠️ 빠른 입력 API을 구현했습니다.
=> [Feat] #77 - 빠른 입력 API 구현

src/main/java/org/example/kuit_kac/domain/user_information/dto/OnboardingRequest.java
closed #93
- 🛠️ 외식 유형에 대한 설명을 추가했습니다.
=> [Feat] #93 - 스웨거 설명 추가

src/main/java/org/example/kuit_kac/config/OAuth2SuccessHandler.java
=> 개발우회용 인증 위한 서명을 url에 원복

src/main/java/org/example/kuit_kac/config/OAuth2SuccessHandler.java, src/main/java/org/example/kuit_kac/domain/home/service/HomeService.java, src/main/java/org/example/kuit_kac/domain/home/service/HomeSummaryService.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml
=> [Chore] 환경변수 수정 및 debug.kid-auth.secret 키 삭제

onboarding.json, src/main/java/org/example/kuit_kac/config/OAuth2SuccessHandler.java, src/main/java/org/example/kuit_kac/domain/home/model/Weight.java, src/main/java/org/example/kuit_kac/domain/home/service/HomeSummaryService.java, src/main/java/org/example/kuit_kac/domain/user_information/controller/OnboardingController.java, src/main/java/org/example/kuit_kac/domain/user_information/dto/OnboardingRequest.java, src/main/java/org/example/kuit_kac/domain/user_information/dto/OnboardingResponse.java, src/main/java/org/example/kuit_kac/domain/user_information/repository/OnboardingStatusPort.java, src/main/java/org/example/kuit_kac/domain/user_information/repository/UserInfoRepository.java, src/main/java/org/example/kuit_kac/domain/user_information/service/OnboardingService.java, src/main/java/org/example/kuit_kac/domain/user_information/service/OnboardingStatusService.java, src/main/java/org/example/kuit_kac/global/util/dev/DevAutofillProperties.java
=> 체중도 온보딩에서 post 반영

src/main/java/org/example/kuit_kac/domain/user_information/controller/OnboardingController.java, src/main/java/org/example/kuit_kac/domain/user_information/dto/OnboardingResponse.java
=> [Chore] /onboarding 스웨거 추가

src/main/java/org/example/kuit_kac/config/OAuth2SuccessHandler.java, src/main/java/org/example/kuit_kac/domain/home/dto/HomeCoachReportResponse.java, src/main/java/org/example/kuit_kac/domain/home/service/CoachReportService.java, src/main/java/org/example/kuit_kac/domain/home/service/HomeSummaryService.java, src/main/java/org/example/kuit_kac/domain/user/controller/UserController.java, src/main/java/org/example/kuit_kac/domain/user_information/service/OnboardingService.java
=> [Chore] 약관필수체크 false로 변경

src/main/java/org/example/kuit_kac/domain/routine/controller/RoutineController.java, src/main/java/org/example/kuit_kac/domain/routine/dto/RoutineTemplateCreateRequest.java, src/main/java/org/example/kuit_kac/domain/routine/dto/RoutineTemplateUpdateRequest.java, src/main/java/org/example/kuit_kac/domain/routine/service/RoutineService.java
closed #129
- 🛠️ 나만의 운동 루틴 API
=> [Feat] #129 - 나만의 운동 루틴 API

src/main/java/org/example/kuit_kac/domain/food/controller/FoodController.java, src/main/java/org/example/kuit_kac/domain/food/dto/FoodResponse.java
closed #131
- 🛠️ response 추가
- 🛠️ API 수정
=> [Fix] #131 - food API response 수정

src/main/java/org/example/kuit_kac/config/OwnerGuard.java, src/main/java/org/example/kuit_kac/config/SecurityConfig.java, src/main/java/org/example/kuit_kac/domain/diet/controller/DietController.java, src/main/java/org/example/kuit_kac/domain/routine/controller/RoutineController.java, src/main/resources/application-dev.yml
=> [Fix] #136 - 임시로 해결 
